services:
  backend:
    image: "mahannezafat/portfolio-backend:latest" 
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@database:5432/postgres
    secrets: 
      - private_key
      - public_key

  frontend:
    build: . 
    ports:
      - "5000:80"

  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}  
      - POSTGRES_USER=${DB_USERNAME}
    secrets:
      - db_password
      - db_username

secrets:
  db_username:
    file: db-username.txt
  db_password:
    file: db-password.txt
  private_key:
    file: secret.pem
  public_key:
    file: public.pem

volumes:
  db_data: 
 