networks:
  frontend-network:
    driver: bridge
    internal: false
  middle-network:
    driver: bridge
    internal: true
  backend-network:
    driver: bridge
    internal: true

services:
  proxy:
    image: "nginx:latest"
    deploy:
      resources:
        limits:
          cpus: '0.25'    
          memory: 256M    
        reservations:     
          cpus: '0.25'    
          memory: 256M 

    ports:
      - "80:80"
    networks:
      - frontend-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
  
    image: "mahannezafat/portfolio-backend:latest"
    deploy:
      resources:
        limits:
          cpus: '0.25'    
          memory: 512M    
        reservations:     
          cpus: '0.25'    
          memory: 512M 

    ports:
      - "3000:3000"
    networks:
      - backend-network
      - middle-network
    depends_on:
      database:
        condition: service_started

    env_file:
      - secret.pem
      - public.pem
      - backend.env



  database:
    image: "postgres:latest"
    deploy:
      resources:
        limits:
          cpus: '0.25'    
          memory: 512M    
        reservations:     
          cpus: '0.25'    
          memory: 512M 
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - db_data:/var/lib/postgresql/data

    env_file:

      - db.env


secrets:
  private_key:
    file: secret.pem
  public_key:
    file: public.pem

volumes:
  db_data: