name: Build Docker Image

on:
  push:
    branches: [dev]
  pull:
   branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
      push: true
      tags: ${{runner.os}}-latest
      file: ./Dockerfile
    - name: login to docker hub
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
